// creative mekanism fluid tank
mods.extendedcrafting.TableCrafting.addShaped("creative_fluid_tank", 0, <item:mekanism:creative_fluid_tank>, [
	[<item:industrialforegoing:supreme_black_hole_tank>, <item:mekanism:uranium_hexafluoride_bucket>, <item:mekanism:heavy_water_bucket>, <item:industrialforegoing:meat_bucket>, <item:mekanism:ultimate_fluid_tank>.withTag({mekData: {owner: [-2094091943, -458931240, -1905311744, -792705749], FluidTanks: [{Tank: 0 as byte, stored: {FluidName: "mekanismgenerators:fusion_fuel" as string, Amount: 1024000 as int}}], securityMode: 0 as int, Items: []}}), <item:industrialforegoing:sludge_bucket>, <item:immersivepetroleum:napalm_bucket>, <item:immersivepetroleum:gasoline_bucket>, <item:industrialforegoing:supreme_black_hole_tank>], 
	[<item:mekanism:superheated_sodium_bucket>, <item:mekanism:ultimate_induction_provider>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:projecte:philosophers_stone>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:mekanism:ultimate_induction_provider>, <item:immersivepetroleum:diesel_sulfur_bucket>], 
	[<item:resourcefulbees:rainbow_honey_fluid_bucket>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:immersivepetroleum:oil_bucket>], 
	[<item:thermal:redstone_bucket>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:draconicevolution:chaotic_core>, <item:projecte:klein_star_omega>, <item:draconicevolution:chaotic_core>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:emendatusenigmatica:molten_arcane_bucket>], 
	[<item:mekanism:ultimate_fluid_tank>.withTag({mekData: {owner: [-2094091943, -458931240, -1905311744, -792705749], FluidTanks: [{Tank: 0 as byte, stored: {FluidName: "mekanismgenerators:fusion_fuel" as string, Amount: 1024000 as int}}], securityMode: 0 as int, Items: []}}), <item:projecte:philosophers_stone>, <item:projecte:red_matter>, <item:projecte:klein_star_omega>, <item:draconicevolution:chaotic_core>, <item:projecte:klein_star_omega>, <item:projecte:red_matter>, <item:projecte:philosophers_stone>, <item:mekanism:ultimate_fluid_tank>.withTag({mekData: {owner: [-2094091943, -458931240, -1905311744, -792705749], FluidTanks: [{Tank: 0 as byte, stored: {FluidName: "mekanismgenerators:fusion_fuel" as string, Amount: 1024000 as int}}], securityMode: 0 as int, Items: []}})], 
	[<item:resourcefulbees:starry_honey_fluid_bucket>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:draconicevolution:chaotic_core>, <item:projecte:klein_star_omega>, <item:draconicevolution:chaotic_core>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:mekanism:oxygen_bucket>], 
	[<item:tconstruct:molten_hepatizon_bucket>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:mekanism:chlorine_bucket>], 
	[<item:charm:bat_bucket>.withTag({stored_bat: {Brain: {memories: {}}, HurtByTimestamp: 0 as int, ForgeData: {"improvedmobs:Breaker": 0 as byte, "improvedmobs:DoEnchant": 1 as byte, "improvedmobs:Flyer": 0 as byte}, Attributes: [{Base: 0.08 as double, Name: "forge:entity_gravity" as string}, {Base: 0.699999988079071 as double, Name: "minecraft:generic.movement_speed" as string}, {Base: 0.0 as double, Name: "minecraft:generic.knockback_resistance" as string}, {Base: 16.0 as double, Modifiers: [{Operation: 1 as int, UUID: [-1449537955, -822915927, -1264687391, -180265477], Amount: 0.06145924200517292 as double, Name: "Random spawn bonus" as string}], Name: "minecraft:generic.follow_range" as string}], Invulnerable: 0 as byte, FallFlying: 0 as byte, PortalCooldown: 0 as int, AbsorptionAmount: 0.0 as float, FallDistance: 0.0 as float, CanUpdate: 1 as byte, DeathTime: 0 as short, ForgeCaps: {"structure_gel:gel_entity": {portal: "structure_gel:empty" as string}, "hats:capability_hat": {hsbH: 0.0 as float, partCount: 0 as int, clrR: 0.0 as float, count: 0 as int, isNew: 0 as byte, hsbS: 0.0 as float, clrG: 0.0 as float, isShowing: 0 as byte, enchanted: 0 as byte, clrA: 0.0 as float, clrB: 0.0 as float, name: "" as string, hsbB: 0.0 as float, isFavourite: 0 as byte}, "mekanism:radiation": {radiation: 1.0E-7 as double}, "twilightforest:cap_shield": {permshields: 0 as int, tempshields: 0 as int}, "mowziesmobs:ability": {}, "mowziesmobs:frozen": {frozenYaw: 0.0 as float, freezeProgress: 0.0 as float, frozenPitch: 0.0 as float, freezeDecayDelay: 0 as int, prevHasAI: 1 as byte, frozenYawHead: 0.0 as float, frozen: 0 as byte, frozenLimbSwingAmount: 0.0 as float, prevFrozen: 0 as byte, frozenRenderYawOffset: 0.0 as float, frozenSwingProgress: 0.0 as float}, "citadel:extended_entity_data_citadel": {}, "eidolon:knowledge": {facts: [], signs: []}}, HandDropChances: [0.085 as float, 0.085 as float], PersistenceRequired: 0 as byte, id: "minecraft:bat" as string, BatFlags: 0 as byte, UUID: [-2125582910, 589253098, -1227771497, -682988434], Motion: [0.1258678080047232 as double, -0.01915822315737551 as double, 0.2068121947065525 as double], Health: 6.0 as float, KubeJSPersistentData: {}, LeftHanded: 0 as byte, Air: 300 as short, OnGround: 0 as byte, CitadelData: {}, Rotation: [-31.32508 as float, 0.0 as float], HandItems: [{}, {}], ArmorDropChances: [0.085 as float, 0.085 as float, 0.085 as float, 0.085 as float], Pos: [-126.87750024300745 as double, 91.11941035314224 as double, -74.09539755331528 as double], Fire: -1 as short, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0 as byte, HurtTime: 0 as short}}), <item:mekanism:ultimate_induction_provider>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:projecte:philosophers_stone>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:mekanism:ultimate_induction_provider>, <item:alexsmobs:platypus_bucket>], 
	[<item:industrialforegoing:supreme_black_hole_tank>, <item:mekanismgenerators:tritium_bucket>, <item:thermal:ender_bucket>, <item:mekanism:lithium_bucket>, <item:mekanism:ultimate_fluid_tank>.withTag({mekData: {owner: [-2094091943, -458931240, -1905311744, -792705749], FluidTanks: [{Tank: 0 as byte, stored: {FluidName: "mekanismgenerators:fusion_fuel" as string, Amount: 1024000 as int}}], securityMode: 0 as int, Items: []}}), <item:thermal:refined_fuel_bucket>, <item:tconstruct:molten_queens_slime_bucket>, <item:mekanismgenerators:deuterium_bucket>, <item:industrialforegoing:supreme_black_hole_tank>]
]);

// creative blaze cake
mods.extendedcrafting.TableCrafting.addShaped("creative_blaze_cake", 0, <item:create:creative_blaze_cake>, [
	[<item:emendatusenigmatica:arcane_block>, <item:emendatusenigmatica:arcane_block>, <item:psi:psimetal_block>, <item:botania:dragonstone_block>, <item:powah:blazing_crystal_block>, <item:botania:dragonstone_block>, <item:psi:psimetal_block>, <item:emendatusenigmatica:arcane_block>, <item:emendatusenigmatica:arcane_block>], 
	[<item:emendatusenigmatica:arcane_block>, <item:pamhc2foodcore:cheesecakeitem>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:pamhc2foodextended:pineappleupsidedowncakeitem>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:pamhc2foodcore:pumpkincheesecakeitem>, <item:emendatusenigmatica:arcane_block>], 
	[<item:psi:psimetal_block>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:psi:psimetal_block>], 
	[<item:botania:dragonstone_block>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:createaddition:chocolate_cake>, <item:minecraft:cake>, <item:createaddition:honey_cake>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:botania:dragonstone_block>], 
	[<item:powah:blazing_crystal_block>, <item:draconicevolution:chaotic_core>, <item:decursiomod:prime_ingot>, <item:tconstruct:sky_cake>, <item:create:blaze_cake>, <item:tconstruct:earth_cake>, <item:decursiomod:prime_ingot>, <item:draconicevolution:chaotic_core>, <item:powah:blazing_crystal_block>], 
	[<item:botania:dragonstone_block>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:tconstruct:blood_cake>, <item:tconstruct:ender_cake>, <item:tconstruct:magma_cake>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:botania:dragonstone_block>], 
	[<item:psi:psimetal_block>, <item:projecte:red_matter>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:decursiomod:prime_ingot>, <item:projecte:red_matter>, <item:psi:psimetal_block>], 
	[<item:emendatusenigmatica:arcane_block>, <item:pamhc2foodextended:chocolatesprinklecakeitem>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:pamhc2foodextended:lemondrizzlecakeitem>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:pamhc2foodcore:carrotcakeitem>, <item:emendatusenigmatica:arcane_block>], 
	[<item:emendatusenigmatica:arcane_block>, <item:emendatusenigmatica:arcane_block>, <item:psi:psimetal_block>, <item:botania:dragonstone_block>, <item:powah:blazing_crystal_block>, <item:botania:dragonstone_block>, <item:psi:psimetal_block>, <item:emendatusenigmatica:arcane_block>, <item:emendatusenigmatica:arcane_block>]
]);

// creative mana pool
mods.extendedcrafting.TableCrafting.addShaped("creative_mana_pool", 0, <item:botania:creative_pool>, [
	[<item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:emendatusenigmatica:arcane_block>, <item:botania:mana_mirror>, <item:projecte:red_matter>, <item:botania:mana_mirror>, <item:emendatusenigmatica:arcane_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>], 
	[<item:botania:terrasteel_block>, <item:appliedenergistics2:64k_cell_component>, <item:decursiomod:prime_ingot_block>, <item:astralsorcery:shifting_star>, <item:botania:rune_spring>, <item:astralsorcery:shifting_star>, <item:decursiomod:prime_ingot_block>, <item:appliedenergistics2:64k_cell_component>, <item:botania:terrasteel_block>], 
	[<item:projecte:high_covalence_dust>, <item:decursiomod:prime_ingot_block>, <item:mythicbotany:mana_ring_greatest>.withTag({mana: 4000000 as int}), <item:botania:rune_wrath>, <item:mythicbotany:alfsteel_block>, <item:botania:rune_winter>, <item:mythicbotany:mana_ring_greatest>.withTag({mana: 4000000 as int}), <item:decursiomod:prime_ingot_block>, <item:projecte:high_covalence_dust>], 
	[<item:projecte:philosophers_stone>, <item:botania:fabulous_pool>, <item:botania:rune_envy>, <item:mythicbotany:alfsteel_block>, <item:draconicevolution:chaotic_core>, <item:mythicbotany:alfsteel_block>, <item:botania:rune_summer>, <item:botania:fabulous_pool>, <item:projecte:philosophers_stone>], 
	[<item:astralsorcery:infuser>, <item:botania:rune_pride>, <item:mythicbotany:alfsteel_block>, <item:endless:infinity_ingot>, <item:mekanism:creative_fluid_tank>, <item:endless:infinity_ingot>, <item:mythicbotany:alfsteel_block>, <item:botania:rune_autumn>, <item:astralsorcery:infuser>], 
	[<item:projecte:philosophers_stone>, <item:botania:fabulous_pool>, <item:botania:rune_sloth>, <item:mythicbotany:alfsteel_block>, <item:draconicevolution:chaotic_core>, <item:mythicbotany:alfsteel_block>, <item:botania:rune_greed>, <item:botania:fabulous_pool>, <item:projecte:philosophers_stone>], 
	[<item:projecte:high_covalence_dust>, <item:decursiomod:prime_ingot_block>, <item:mythicbotany:mana_ring_greatest>.withTag({mana: 4000000 as int}), <item:botania:rune_mana>, <item:mythicbotany:alfsteel_block>, <item:botania:rune_gluttony>, <item:mythicbotany:mana_ring_greatest>.withTag({mana: 4000000 as int}), <item:decursiomod:prime_ingot_block>, <item:projecte:high_covalence_dust>], 
	[<item:botania:terrasteel_block>, <item:appliedenergistics2:64k_cell_component>, <item:decursiomod:prime_ingot_block>, <item:astralsorcery:shifting_star>, <item:botania:rune_lust>, <item:astralsorcery:shifting_star>, <item:decursiomod:prime_ingot_block>, <item:appliedenergistics2:64k_cell_component>, <item:botania:terrasteel_block>], 
	[<item:botania:terrasteel_block>, <item:botania:terrasteel_block>, <item:emendatusenigmatica:arcane_block>, <item:botania:mana_mirror>, <item:projecte:red_matter>, <item:botania:mana_mirror>, <item:emendatusenigmatica:arcane_block>, <item:botania:terrasteel_block>, <item:botania:terrasteel_block>]
]);

// creative create motor
mods.extendedcrafting.TableCrafting.addShaped("creative_motor", 0, <item:create:creative_motor>, [
	[<item:decursiomod:prime_ingot_block>, <item:decursiomod:prime_ingot_block>, <item:powah:reactor_nitro>, <item:mekanism:ultimate_tier_installer>, <item:projecte:dark_matter_block>, <item:mekanism:ultimate_tier_installer>, <item:powah:reactor_nitro>, <item:decursiomod:prime_ingot_block>, <item:decursiomod:prime_ingot_block>], 
	[<item:decursiomod:prime_ingot_block>, <item:draconicevolution:draconium_block>, <item:thermal:dynamo_compression>, <item:thermal:upgrade_augment_3>, <item:thermal:upgrade_augment_3>, <item:thermal:upgrade_augment_3>, <item:thermal:dynamo_stirling>, <item:draconicevolution:draconium_block>, <item:decursiomod:prime_ingot_block>], 
	[<item:powah:reactor_nitro>, <item:thermal:dynamo_compression>, <item:createaddition:overcharged_casing>, <item:draconicevolution:draconic_capacitor>, <item:draconicevolution:draconic_capacitor>, <item:draconicevolution:draconic_capacitor>, <item:createaddition:overcharged_casing>, <item:thermal:dynamo_stirling>, <item:powah:reactor_nitro>], 
	[<item:mekanismgenerators:rotational_complex>, <item:thermal:upgrade_augment_3>, <item:draconicevolution:draconic_capacitor>, <item:draconicevolution:reactor_core>, <item:projecte:red_matter_block>, <item:draconicevolution:reactor_core>, <item:draconicevolution:draconic_capacitor>, <item:thermal:upgrade_augment_3>, <item:mekanismgenerators:rotational_complex>], 
	[<item:projecte:dark_matter_block>, <item:thermal:upgrade_augment_3>, <item:draconicevolution:draconic_capacitor>, <item:projecte:red_matter_block>, <item:draconicevolution:reactor_core>, <item:projecte:red_matter_block>, <item:draconicevolution:draconic_capacitor>, <item:thermal:upgrade_augment_3>, <item:projecte:dark_matter_block>], 
	[<item:mekanismgenerators:rotational_complex>, <item:thermal:upgrade_augment_3>, <item:draconicevolution:draconic_capacitor>, <item:draconicevolution:reactor_core>, <item:projecte:red_matter_block>, <item:draconicevolution:reactor_core>, <item:draconicevolution:draconic_capacitor>, <item:thermal:upgrade_augment_3>, <item:mekanismgenerators:rotational_complex>], 
	[<item:powah:reactor_nitro>, <item:thermal:dynamo_stirling>, <item:createaddition:overcharged_casing>, <item:draconicevolution:draconic_capacitor>, <item:draconicevolution:draconic_capacitor>, <item:draconicevolution:draconic_capacitor>, <item:createaddition:overcharged_casing>, <item:thermal:dynamo_compression>, <item:powah:reactor_nitro>], 
	[<item:decursiomod:prime_ingot_block>, <item:draconicevolution:draconium_block>, <item:thermal:dynamo_stirling>, <item:thermal:upgrade_augment_3>, <item:thermal:upgrade_augment_3>, <item:thermal:upgrade_augment_3>, <item:thermal:dynamo_compression>, <item:draconicevolution:draconium_block>, <item:decursiomod:prime_ingot_block>], 
	[<item:decursiomod:prime_ingot_block>, <item:decursiomod:prime_ingot_block>, <item:powah:reactor_nitro>, <item:mekanism:ultimate_tier_installer>, <item:projecte:dark_matter_block>, <item:mekanism:ultimate_tier_installer>, <item:powah:reactor_nitro>, <item:decursiomod:prime_ingot_block>, <item:decursiomod:prime_ingot_block>]
]);

// creative ae2 me storage cell
mods.extendedcrafting.TableCrafting.addShaped("creative_storage_cell", 0, <item:appliedenergistics2:creative_storage_cell>, [
	[<item:decursiomod:prime_ingot_block>, <item:emendatusenigmatica:iridium_plate>, <item:emendatusenigmatica:iridium_plate>, <item:emendatusenigmatica:iridium_gear>, <item:emendatusenigmatica:iridium_block>, <item:emendatusenigmatica:iridium_gear>, <item:emendatusenigmatica:iridium_plate>, <item:emendatusenigmatica:iridium_plate>, <item:decursiomod:prime_ingot_block>], 
	[<item:emendatusenigmatica:iridium_plate>, <item:mekanism:qio_drive_supermassive>, <item:thermal:upgrade_augment_3>, <item:decursiomod:prime_ingot>, <item:decursiomod:electrolysed_alloy>.withTag({Energy: 4800 as int}), <item:decursiomod:prime_ingot>, <item:thermal:upgrade_augment_3>, <item:mekanism:qio_drive_supermassive>, <item:emendatusenigmatica:iridium_plate>], 
	[<item:emendatusenigmatica:iridium_plate>, <item:thermal:upgrade_augment_3>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:thermal:upgrade_augment_3>, <item:emendatusenigmatica:iridium_plate>], 
	[<item:emendatusenigmatica:iridium_gear>, <item:decursiomod:prime_ingot>, <item:appliedenergistics2:64k_cell_component>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_control_circuit>, <item:appliedenergistics2:64k_cell_component>, <item:decursiomod:prime_ingot>, <item:emendatusenigmatica:iridium_gear>], 
	[<item:emendatusenigmatica:iridium_block>, <item:decursiomod:electrolysed_alloy>.withTag({Energy: 4800 as int}), <item:appliedenergistics2:64k_cell_component>, <item:mekanism:ultimate_control_circuit>, <item:draconicevolution:chaotic_core>, <item:mekanism:ultimate_control_circuit>, <item:appliedenergistics2:64k_cell_component>, <item:decursiomod:electrolysed_alloy>.withTag({Energy: 4800 as int}), <item:emendatusenigmatica:iridium_block>], 
	[<item:emendatusenigmatica:iridium_gear>, <item:decursiomod:prime_ingot>, <item:appliedenergistics2:64k_cell_component>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_control_circuit>, <item:appliedenergistics2:64k_cell_component>, <item:decursiomod:prime_ingot>, <item:emendatusenigmatica:iridium_gear>], 
	[<item:emendatusenigmatica:iridium_plate>, <item:thermal:upgrade_augment_3>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_cell_component>, <item:thermal:upgrade_augment_3>, <item:emendatusenigmatica:iridium_plate>], 
	[<item:emendatusenigmatica:iridium_plate>, <item:mekanism:qio_drive_supermassive>, <item:thermal:upgrade_augment_3>, <item:decursiomod:prime_ingot>, <item:decursiomod:electrolysed_alloy>.withTag({Energy: 4800 as int}), <item:decursiomod:prime_ingot>, <item:thermal:upgrade_augment_3>, <item:mekanism:qio_drive_supermassive>, <item:emendatusenigmatica:iridium_plate>], 
	[<item:decursiomod:prime_ingot_block>, <item:emendatusenigmatica:iridium_plate>, <item:emendatusenigmatica:iridium_plate>, <item:emendatusenigmatica:iridium_gear>, <item:emendatusenigmatica:iridium_block>, <item:emendatusenigmatica:iridium_gear>, <item:emendatusenigmatica:iridium_plate>, <item:emendatusenigmatica:iridium_plate>, <item:decursiomod:prime_ingot_block>]
]);